name: Xform
channels:
  - conda-forge
  - defaults
dependencies:
  - assimulo=3.0
  - boost-cpp=1.68.0
  - ca-certificates=2019.6.16
  - certifi=2019.3.9
  - fenics=2019.1.0
  - fenics-dijitso=2019.1.0
  - fenics-dolfin=2019.1.0
  - fenics-ffc=2019.1.0
  - fenics-fiat=2019.1.0
  - fenics-libdolfin=2019.1.0
  - fenics-ufl=2019.1.0
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - hdf5=1.10.4
  - hypre=2.15.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - mpfr=4.0.2
  - mpi4py=3.0.1
  - mshr=2019.1.0
  - mumps-include=5.1.2
  - mumps-mpi=5.1.2
  - openssl=1.1.1b
  - parmetis=4.0.3
  - petsc=3.11.1
  - petsc4py=3.11.0
  - ptscotch=6.0.6
  - scalapack=2.0.2
  - scipy=1.3.0
  - scotch=6.0.6
  - slepc=3.11.1
  - slepc4py=3.11.0
  - suitesparse=4.5.6
  - sundials=3.2.1
  - tbb=2019.7
  - attrs=19.1.0
  - backcall=0.1.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.6
  - cmake=3.12.2
  - curl=7.64.1
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - eigen=3.3.7
  - entrypoints=0.3
  - expat=2.2.6
  - fastcache=1.1.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gmp=6.1.2
  - gmpy2=2.0.8
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.64.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libiconv=1.
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libuv=1.26.0
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - metis=5.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mpc=1.1.0
  - mpi=1.0
  - mpich=3.2.1
  - mpmath=1.1.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1.1
  - pkg-config=0.29.2
  - pkgconfig=1.3.1
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pybind11=2.2.4
  - pygments=2.4.2
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.1
  - readline=7.0
  - rhash=1.3.6
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - sympy=1.4
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
prefix: /softs/Utils/anaconda3/envs/Xform
