name: fenicsproject
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - assimulo=3.0
  - astroid=2.2.5
  - attrs=19.1.0
  - babel=2.6.0
  - backcall=0.1.0
  - bleach=3.1.0
  - boost-cpp=1.68.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - cloudpickle=1.0.0
  - cmake=3.14.3
  - cryptography=2.6.1
  - curl=7.64.1
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - docutils=0.14
  - eigen=3.3.7
  - entrypoints=0.3
  - expat=2.2.5
  - fastcache=1.1.0
  - fenics=2019.1.0
  - fenics-dijitso=2019.1.0
  - fenics-dolfin=2019.1.0
  - fenics-ffc=2019.1.0
  - fenics-fiat=2019.1.0
  - fenics-libdolfin=2019.1.0
  - fenics-ufl=2019.1.0
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gmp=6.1.2
  - gmpy2=2.0.8
  - hdf5=1.10.4
  - hypre=2.15.1
  - icu=58.2
  - idna=2.8
  - imagesize=1.1.0
  - ipykernel=5.1.0
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - isort=4.3.20
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - keyring=19.0.1
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - lazy-object-proxy=1.4.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libuv=1.28.0
  - llvmlite=0.28.0
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mccabe=0.6.1
  - metis=5.1.0
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpi4py=3.0.1
  - mpich=3.2.1
  - mpmath=1.1.0
  - mshr=2019.1.0
  - mumps-include=5.1.2
  - mumps-mpi=5.1.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numba=0.43.1
  - numpy=1.15.4
  - numpydoc=0.9.1
  - openblas=0.3.6
  - openssl=1.1.1b
  - packaging=19.0
  - pandoc=2.7.2
  - pandocfilters=1.4.2
  - parmetis=4.0.3
  - parso=0.4.0
  - pcre=8.41
  - petsc=3.11.1
  - petsc4py=3.11.0
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1
  - pkg-config=0.29.2
  - pkgconfig=1.3.1
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - psutil=5.6.2
  - ptscotch=6.0.6
  - ptyprocess=0.6.0
  - pybind11=2.2.4
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pygments=2.4.0
  - pylint=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt=5.6.0
  - pyrsistent=0.15.2
  - pysocks=1.7.0
  - python=3.7.3
  - python-dateutil=2.8.0
  - python.app=1.2
  - pytz=2019.1
  - pyzmq=18.0.1
  - qt=5.6.2
  - qtawesome=0.5.7
  - qtconsole=4.4.4
  - qtpy=1.7.1
  - readline=7.0
  - requests=2.22.0
  - rhash=1.3.6
  - rope=0.14.0
  - scalapack=2.0.2
  - scikit-sparse=0.4.4
  - scipy=1.2.1
  - scotch=6.0.6
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.18.1
  - six=1.12.0
  - slepc=3.11.0
  - slepc4py=3.11.0
  - snowballstemmer=1.2.1
  - sphinx=2.0.1
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.1
  - spyder=3.3.4
  - spyder-kernels=0.4.4
  - sqlite=3.26.0
  - suitesparse=4.5.6
  - sundials=3.2.1
  - sympy=1.4
  - tbb=2019.4
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.2
  - traitlets=4.3.2
  - urllib3=1.24.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - wrapt=1.11.1
  - wurlitzer=1.0.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - diffeqpy==1.0.0
    - julia==0.4.1
prefix: /Users/vasseur/Software/anaconda3/envs/fenicsproject
